version: "3.9"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_SERVER: db
      DB_DATABASE: admin
      DB_PORT: 5432
      PORT: 8080
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  pgdata:
    driver: local